apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-web
  labels:
    app: shop-web
    version: v1
spec:
  selector:
    matchLabels:
      app: shop-web
  template:
    metadata:
      labels:
        app: shop-web
        version: v1
    spec:
      serviceAccountName: shop-web-sa
      containers:
        - name: shop-web
          image: tgitech/expresso-project:web
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: shop-web-config

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shop-web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shop-web
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: v1
kind: Service
metadata:
  name: shop-web
spec:
  type: LoadBalancer 
  selector:
    app: shop-web
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-web-config
data:
  ProductCatalogUrl: "http://shop-product-catalog:8091"
  ReviewsUrl: "http://shop-reviews:8092"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shop-web-sa



