NAME: front-end
LAST DEPLOYED: Tue Mar 18 12:19:27 2025
NAMESPACE: expresso
STATUS: pending-install
REVISION: 1
HOOKS:
---
# Source: front-end/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "shop-web-test-connection"
  labels:
    
    app: shop-web
    version: v1
    
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['shop-web:8090']
  restartPolicy: Never
MANIFEST:
---
# Source: front-end/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shop-web-sa
---
# Source: front-end/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-web-config
data:
  ProductCatalogUrl: http://shop-product-catalog:8091
  ReviewsUrl: http://shop-reviews:8092
---
# Source: front-end/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: shop-web
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 80
      protocol: TCP
  selector:
    app: shop-web
---
# Source: front-end/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-web
  labels:
    
    app: shop-web
    version: v1
    
spec:
  selector:
    matchLabels:
      app: shop-web
      version: v1
  template:
    metadata:
      labels:
        
        app: shop-web
        version: v1
        
    spec:
      serviceAccountName: shop-web-sa
      containers:
        - name: front-end
          image: "tgitech/expresso-project:web"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          envFrom:
            - configMapRef:
                name: shop-web-config
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
# Source: front-end/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shop-web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shop-web
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

NOTES:
1. Get the application URL by running these commands:
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch its status by running 'kubectl get --namespace expresso svc -w shop-web'
  export SERVICE_IP=$(kubectl get svc --namespace expresso shop-web --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo http://$SERVICE_IP:8090
