apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopreview.fullname" . }}
  labels:
    version: {{ .Values.deployment.version }}
    version: {{ .Values.deployment.version2 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.deployment.name }}
    app: {{ .Values.deployment.name2 }}
    